- name: Run shipping container
  containers.podman.podman_container:
    name: shipping
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
    state: started
    ports:
      - "8080:8080"
    env:
      CART_ENDPOINT: "{{ secrets.CART_ENDPOINT }}"
      DB_HOST: "{{ secrets.DB_HOST }}"

- name: load schema container
  loop:
    - app-user
    - schema
    - master-data

  containers.podman.podman_container:
    name: "{{ item }}"
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE: "{{ secrets.DB_TYPE }}"
      APP_GIT_URL: "{{ secrets.APP_GIT_URL }}"
      DB_HOST: "{{ secrets.DB_HOST }}"
      DB_USER:  "{{ secrets.MYSQL_ROOT_USER }}"
      DB_PASS: "{{ secrets.MYSQL_ROOT_PASSWORD }}"
      SCHEMA_FILE: "db/master-data.sql"



