- name: Run user container
  containers.podman.podman_container:
    name: user
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
    state: started
    ports:
      - "8080:8080"
    env:
      MONGO:  "{{ secrets.MONGO }}"
      REDIS_URL: "{{ secrets.REDIS_URL }}"
      MONGO_URL: "{{ secrets.MONGO_URL }}"