- name: Run catalogue container
  containers.podman.podman_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    state: started
    ports:
      - "8080:8080"
    env:
      MONGO:     "{{ secrets.MONGO }}"
      MONGO_URL: "{{ secrets.MONGO_URL }}"

- name: Run master data load container
  containers.podman.podman_container:
    name: master-data-load
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE : "{{ secrets.DB_TYPE }}"
      DB_HOST : "{{ secrets.DB_HOST }}"
      APP_GIT_URL: "{{ secrets.APP_GIT_URL }}"
      SCHEMA_FILE: "{{ secrets.SCHEMA_FILE }}"
