- name: Load MongoDb Schema
  when: schema_setup == "mongo"
  block:
    - name: COpy MongoDB repo file
      ansible.builtin.template:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: latest

    - name: Load Master Data
      ansible.builtin.shell: mongosh --host mongo.{{ env }}.sy80devops.online < /app/db/{{ item }}.js
      loop: "{{ schema_files }}"

- name: Load mysql Schema
  when: schema_setup == "mysql"
  block:
    - name:  Install MySQL Client
      ansible.builtin.dnf:
        name: mysql
        state: latest

    - name: load Master data
      ansible.builtin.shell: mysql -h mysql.{{ env }}.sy80devops.online -uroot -p{{ secrets.MYSQL_ROOT_PASSWORD }} <
      /app/db/{{ item }}.sql
      loop: "{{ schema_files }}"


