component: catalogue
app_path: /app
schema_setup: mongo
schema_files:
  - master-data

secrets: "{{ lookup('hashi_vault', 'secret=Roboshop-{{env}}/data/catalogue token={{vault_token}} url=https://vault.sydevops80.online:8200 validate_certs=false')}}"
